apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: get-task-ingress
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: gettask.devops-engineer-adda.store
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: get-task
            port: 
              number: 80
